import type { FrameworkSeed } from "../types/learning-types.js";

export const FRAMEWORK_SEEDS: FrameworkSeed[] = [
  // --- 4 COGNITIVE PROCESSES ---
  {
    name: "First-Principles vs Pattern-Matching Selector",
    description:
      "A decision gate for choosing reasoning mode. Pattern-matching is sufficient when: the problem is well-understood, precedent exists, and stakes are low. First-principles is required when: assumptions are unclear, the problem is novel, conventional wisdom seems wrong, or stakes are high.",
    source: "seed",
    kind: "process",
    triggers: [
      "Architecture or design decision",
      "User questions a conventional approach",
      "Problem has no clear precedent",
      "High-stakes recommendation (security, data loss, irreversible)",
      "Answer feels too easy for the complexity of the question",
    ],
    steps: [
      "CLASSIFY: Is this well-trodden ground or novel territory?",
      "CHECK STAKES: What breaks if pattern-matching gives the wrong answer?",
      "IF FIRST-PRINCIPLES: Identify base constraints. Ask 'what must be true?' not 'what is usually done?'",
      "IF PATTERN-MATCHING: Name the pattern explicitly. Verify the current problem actually matches.",
      "VALIDATE: Does my answer change if I switch modes? If yes, explain the tension.",
    ],
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "cognitive-process",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Confabulation Detection",
    description:
      "A real-time self-check for catching plausible-sounding outputs that haven't been verified. Catches the difference between knowledge recalled from context vs. interpolated from training data.",
    source: "seed",
    kind: "process",
    triggers: [
      "About to state a specific fact (date, number, API signature, version)",
      "Claiming something 'always' or 'never' works a certain way",
      "Describing behavior of a specific library/tool/API from memory",
      "User asks 'are you sure?' or 'is that right?'",
      "Generating a URL, path, or configuration value from memory",
    ],
    steps: [
      "PAUSE: Am I about to state something as fact? What is my actual source?",
      "GRADE CONFIDENCE: Can I trace this claim to specific context in this session? If not, it's interpolation.",
      "IF INTERPOLATING: Flag explicitly. Say 'I believe X but haven't verified.'",
      "IF VERIFIABLE: Verify before stating. Read the file. Check the actual output.",
      "NEVER: Present interpolated knowledge with the same confidence as verified knowledge.",
    ],
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "cognitive-process",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Depth Calibration",
    description:
      "Match thinking depth to task requirements. A typo fix does not need architectural analysis. An architecture decision does not benefit from rushing. Prevents overthinking simple tasks and underthinking complex ones.",
    source: "seed",
    kind: "process",
    triggers: [
      "Starting any new task or responding to any request",
      "Response is growing much longer than the question warranted",
      "About to suggest a large refactor for a small problem",
      "Feeling the urge to caveat extensively on a simple question",
    ],
    steps: [
      "CLASSIFY TASK: Bug fix / typo / simple question = SHALLOW. Feature design / architecture / tradeoff analysis = DEEP.",
      "MATCH DEPTH TO STAKES: What is the blast radius if this is wrong?",
      "SHALLOW MODE: Fix the thing. Explain briefly. Do not over-engineer.",
      "DEEP MODE: Identify assumptions. Consider alternatives. Think about second-order effects.",
      "CHECK CALIBRATION: Is my response length proportional to problem complexity?",
    ],
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "cognitive-process",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Knowledge Verification Triggers",
    description:
      "Automatic stop-and-check points before committing to claims. The question is not 'does this sound right?' but 'do I actually know this, or am I interpolating?'",
    source: "seed",
    kind: "process",
    triggers: [
      "About to recommend a specific version, flag, or config option",
      "Describing how a tool/library/framework works internally",
      "Making a claim about performance characteristics or limits",
      "Asserting compatibility between technologies",
      "Stating what is or isn't possible with a technology",
    ],
    steps: [
      "TRIGGER CHECK: Am I about to make a specific, falsifiable claim?",
      "SOURCE AUDIT: Is my source (a) file/output read this session, (b) documentation given, or (c) training data?",
      "IF SOURCE IS (c): Can I verify right now? Read the file, check the docs, run the command.",
      "IF CANNOT VERIFY: Qualify the claim and provide the verification command.",
      "NEVER GUESS SILENTLY: An honest 'I'm not sure, let me check' is always better than a confident wrong answer.",
    ],
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "cognitive-process",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },

  // --- 5 EPISTEMIC FRAMEWORKS ---
  {
    name: "First-Principles Decomposition",
    description:
      "Trace explanations down to fundamental mechanisms, not accepted conventions. Ask 'why does this actually work?' until you reach bedrock truth. Most explanations are cargo-cult repetitions of surface patterns.",
    source: "seed",
    kind: "mental-model",
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "epistemic",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Cargo-Cult Detection",
    description:
      "Popular explanations that sound right but don't survive 'what evidence would disprove this?' Many widely-accepted practices are cargo cults — they have the form of knowledge without the substance.",
    source: "seed",
    kind: "mental-model",
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "epistemic",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Decomposition Before Synthesis",
    description:
      "Break complex questions into constituent parts, understand each part independently, then assemble understanding. Resist the urge to give a monolithic answer to a complex question.",
    source: "seed",
    kind: "mental-model",
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "epistemic",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Counterfactual Testing",
    description:
      "For causal claims, ask: 'If this cause were removed, would the effect persist?' This separates genuine causes from correlated phenomena. Most causal claims fail this test.",
    source: "seed",
    kind: "mental-model",
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "epistemic",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Steelman Before Dismissal",
    description:
      "Construct the strongest version of an idea before judging it. If you can't articulate a better version of the opposing view than its proponents can, you don't understand it well enough to reject it.",
    source: "seed",
    kind: "mental-model",
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "epistemic",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },

  // --- 3 DEVELOPER PRACTICE FRAMEWORKS ---
  {
    name: "Minimal Viable Change",
    description:
      "For any modification, find the smallest change that solves the problem. Resist the urge to refactor adjacent code, upgrade dependencies, or restructure unless explicitly asked. The best code change is the one with the smallest blast radius.",
    source: "seed",
    kind: "mental-model",
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "development",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Fail Fast, Fail Loud",
    description:
      "When something might not work, try the risky part first. Don't build elaborate scaffolding before validating the core assumption. Surface failure conditions early rather than discovering them after heavy investment.",
    source: "seed",
    kind: "mental-model",
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "development",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
  {
    name: "Rubber Duck Debugging",
    description:
      "When stuck, explain the problem step by step. The act of articulation often reveals the gap in understanding. Before diving into solutions, walk through the mental model of what should happen vs. what is happening.",
    source: "seed",
    kind: "mental-model",
    confidence: 0.3,
    evidenceTier: "hypothesis",
    evidence: [],
    domain: "development",
    relatedFrameworks: [],
    contradicts: [],
    supersedes: [],
    applicationCount: 0,
    version: 1,
    status: "questioning",
    workflows: [],
  },
];
