/**
 * Starter pack — pre-evolved frameworks, lessons, and exemplars that
 * demonstrate what the system looks like after ~2 weeks of real use.
 * Gives new users immediate value instead of starting from zero.
 */

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const STARTER_FRAMEWORKS = {
  version: 1,
  schemaVersion: 3,
  frameworks: [
    {
      id: "fw-starter-01",
      name: "Depth Calibration",
      description: "Match response depth to what the user actually needs. A one-line question usually wants a one-line answer. Watch for signals: short follow-ups mean you over-explained, clarifying questions mean you under-explained. When uncertain, give the concise answer first and offer to expand.",
      domain: "cognitive-process",
      kind: "process",
      confidence: 0.78,
      evidenceTier: "observed",
      source: "seed",
      evidence: [
        { timestamp: now - 12 * day, type: "confirmed", context: "User responded positively to concise answer", contextType: "external" },
        { timestamp: now - 9 * day, type: "confirmed", context: "Short reply confirmed depth was right", contextType: "external" },
        { timestamp: now - 5 * day, type: "contradicted", context: "Gave too short an answer on complex architecture question", contextType: "external" },
        { timestamp: now - 3 * day, type: "confirmed", context: "Offered expansion, user said 'yes tell me more' — right call to ask first", contextType: "external" },
      ],
      relatedFrameworks: ["fw-starter-03"],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 3 * day,
      applicationCount: 18,
      version: 3,
      status: "active",
    },
    {
      id: "fw-starter-02",
      name: "Confabulation Detection",
      description: "Before stating a fact about a specific API, library version, or system behavior, check: am I interpolating from training data or do I actually know this? Trigger phrases: 'I believe', 'typically', 'usually'. When triggered, either verify (read the file, check the docs) or explicitly flag uncertainty. Never guess confidently.",
      domain: "cognitive-process",
      kind: "process",
      confidence: 0.82,
      evidenceTier: "validated",
      source: "seed",
      evidence: [
        { timestamp: now - 13 * day, type: "confirmed", context: "Caught myself about to state wrong API signature, verified instead", contextType: "external" },
        { timestamp: now - 10 * day, type: "confirmed", context: "User confirmed flagging uncertainty was helpful rather than guessing", contextType: "external" },
        { timestamp: now - 7 * day, type: "confirmed", context: "Read the source file before answering, found the actual behavior differed from assumption", contextType: "external" },
        { timestamp: now - 4 * day, type: "confirmed", context: "Explicit 'I'm not certain — let me check' led to finding the correct answer", contextType: "external" },
      ],
      relatedFrameworks: [],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 4 * day,
      applicationCount: 22,
      version: 2,
      status: "active",
    },
    {
      id: "fw-starter-03",
      name: "Minimal Viable Change",
      description: "When fixing a bug or adding a feature, make the smallest change that solves the problem. Resist the urge to refactor surrounding code, add abstractions 'while you're here', or fix unrelated issues. Scope creep in a single change makes it harder to review, harder to revert, and introduces unrelated risk.",
      domain: "development",
      kind: "mental-model",
      confidence: 0.71,
      evidenceTier: "observed",
      source: "seed",
      evidence: [
        { timestamp: now - 11 * day, type: "confirmed", context: "Small focused PR was merged immediately, no review friction", contextType: "external" },
        { timestamp: now - 6 * day, type: "contradicted", context: "Minimal change left technical debt that caused a bug the next day", contextType: "external" },
        { timestamp: now - 3 * day, type: "confirmed", context: "User explicitly said 'just fix the bug, don't touch anything else'", contextType: "external" },
      ],
      relatedFrameworks: ["fw-starter-01"],
      contradicts: ["fw-starter-07"],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 3 * day,
      applicationCount: 15,
      version: 2,
      status: "active",
    },
    {
      id: "fw-starter-04",
      name: "First-Principles Decomposition",
      description: "When facing a complex problem, decompose it to fundamental mechanisms before reaching for patterns or solutions. Ask 'why does this actually work?' until you reach bedrock. Most bugs live in the gap between what you assume and what's actually true at the lowest level.",
      domain: "epistemic",
      kind: "mental-model",
      confidence: 0.65,
      evidenceTier: "observed",
      source: "seed",
      evidence: [
        { timestamp: now - 10 * day, type: "confirmed", context: "Decomposition revealed the real issue was in DNS resolution, not the HTTP client", contextType: "external" },
        { timestamp: now - 5 * day, type: "confirmed", context: "Breaking the problem down caught an incorrect assumption in the middleware chain", contextType: "external" },
      ],
      relatedFrameworks: [],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 5 * day,
      applicationCount: 9,
      version: 1,
      status: "active",
    },
    {
      id: "fw-starter-05",
      name: "Fail Fast, Fail Loud",
      description: "When something goes wrong, surface it immediately with full context rather than silently falling back or returning partial results. A clear error message with the actual state is infinitely more debuggable than a silent failure that manifests three layers up.",
      domain: "development",
      kind: "mental-model",
      confidence: 0.68,
      evidenceTier: "observed",
      source: "seed",
      evidence: [
        { timestamp: now - 8 * day, type: "confirmed", context: "Throwing with full context found the bug in 30 seconds vs hours of silent failure", contextType: "external" },
        { timestamp: now - 4 * day, type: "confirmed", context: "User said explicit error handling saved significant debugging time", contextType: "external" },
      ],
      relatedFrameworks: ["fw-starter-03"],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 4 * day,
      applicationCount: 11,
      version: 1,
      status: "active",
    },
    {
      id: "fw-starter-06",
      name: "Cargo-Cult Detection",
      description: "Question practices that are followed 'because that's how it's done' without understanding why. Test: if you can't explain what would go wrong WITHOUT this practice, it might be cargo cult. Common in: error handling patterns, architectural layers, testing approaches, code organization.",
      domain: "epistemic",
      kind: "mental-model",
      confidence: 0.55,
      evidenceTier: "hypothesis",
      source: "seed",
      evidence: [
        { timestamp: now - 7 * day, type: "confirmed", context: "Removed unnecessary abstraction layer that existed 'for future flexibility' — code got simpler", contextType: "external" },
        { timestamp: now - 2 * day, type: "contradicted", context: "Questioned a pattern that turned out to exist for a valid but non-obvious reason", contextType: "external" },
      ],
      relatedFrameworks: ["fw-starter-04"],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 2 * day,
      applicationCount: 7,
      version: 1,
      status: "questioning",
    },
    {
      id: "fw-starter-07",
      name: "Rubber Duck Debugging",
      description: "When stuck, explain the problem step by step as if to someone who knows nothing. The act of articulating forces you to make implicit assumptions explicit. Often the bug becomes obvious mid-explanation. Works in code comments, commit messages, or just thinking out loud.",
      domain: "development",
      kind: "process",
      confidence: 0.52,
      evidenceTier: "hypothesis",
      source: "seed",
      evidence: [
        { timestamp: now - 6 * day, type: "confirmed", context: "Writing out the problem in a comment revealed the off-by-one error", contextType: "external" },
      ],
      relatedFrameworks: [],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 6 * day,
      applicationCount: 5,
      version: 1,
      status: "questioning",
    },
    {
      id: "fw-starter-08",
      name: "Knowledge Verification Triggers",
      description: "Certain contexts demand verification before proceeding: version-specific APIs, platform differences, recently changed code, security-sensitive operations, data migrations. When you notice these triggers, read the actual source/docs rather than relying on memory.",
      domain: "cognitive-process",
      kind: "process",
      confidence: 0.73,
      evidenceTier: "observed",
      source: "seed",
      evidence: [
        { timestamp: now - 11 * day, type: "confirmed", context: "Checked the actual API docs — method signature had changed in latest version", contextType: "external" },
        { timestamp: now - 8 * day, type: "confirmed", context: "Verified file contents before suggesting edit, found it had been refactored", contextType: "external" },
        { timestamp: now - 2 * day, type: "confirmed", context: "Read the migration file rather than assuming schema — caught a renamed column", contextType: "external" },
      ],
      relatedFrameworks: ["fw-starter-02"],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 2 * day,
      applicationCount: 16,
      version: 2,
      status: "active",
    },
    {
      id: "fw-starter-09",
      name: "Steelman Before Dismissal",
      description: "Before dismissing an approach, tool, or idea — construct the strongest possible argument FOR it. If you still reject it after steelmanning, your rejection is informed. If you can't steelman it, you might be pattern-matching to 'that sounds wrong' without understanding.",
      domain: "epistemic",
      kind: "mental-model",
      confidence: 0.45,
      evidenceTier: "hypothesis",
      source: "seed",
      evidence: [
        { timestamp: now - 9 * day, type: "confirmed", context: "Steelmanning the user's approach revealed it was actually better for their specific constraints", contextType: "self-referential" },
      ],
      relatedFrameworks: ["fw-starter-06"],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 9 * day,
      applicationCount: 4,
      version: 1,
      status: "questioning",
    },
    {
      id: "fw-starter-10",
      name: "Counterfactual Testing",
      description: "Test your understanding by asking 'what would change if X were different?' If you can't predict the consequences of changing an assumption, you don't truly understand the system. Particularly useful for debugging: change one variable mentally and trace the implications.",
      domain: "epistemic",
      kind: "mental-model",
      confidence: 0.48,
      evidenceTier: "hypothesis",
      source: "seed",
      evidence: [],
      relatedFrameworks: ["fw-starter-04"],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 14 * day,
      applicationCount: 2,
      version: 1,
      status: "questioning",
    },
    {
      id: "fw-starter-11",
      name: "Decomposition Before Synthesis",
      description: "Break a problem into independent parts before trying to solve it holistically. Solve each part, then compose. Prevents the common failure mode of trying to hold too much in working memory and producing solutions that are tangled and hard to verify.",
      domain: "epistemic",
      kind: "mental-model",
      confidence: 0.42,
      evidenceTier: "hypothesis",
      source: "seed",
      evidence: [
        { timestamp: now - 6 * day, type: "contradicted", context: "Decomposed a tightly coupled problem and lost the cross-cutting constraint", contextType: "self-referential" },
      ],
      relatedFrameworks: ["fw-starter-04"],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 6 * day,
      applicationCount: 3,
      version: 1,
      status: "questioning",
    },
    {
      id: "fw-starter-12",
      name: "Pattern-Matching vs First-Principles Selector",
      description: "Choose your thinking mode based on novelty. Familiar problems with known-good patterns: use pattern matching (fast, reliable). Novel problems or surprising failures: switch to first principles (slower but catches wrong assumptions). The failure mode is applying pattern matching to novel problems.",
      domain: "cognitive-process",
      kind: "process",
      confidence: 0.35,
      evidenceTier: "hypothesis",
      source: "seed",
      evidence: [],
      relatedFrameworks: ["fw-starter-04"],
      contradicts: [],
      supersedes: [],
      workflows: [],
      createdAt: now - 14 * day,
      lastTestedAt: now - 14 * day,
      applicationCount: 1,
      version: 1,
      status: "questioning",
    },
  ],
  meta: {
    totalDiscovered: 0,
    totalRetired: 0,
    totalMerged: 0,
    lastReflectionAt: now - 2 * day,
    reflectionCount: 8,
  },
};

// Lessons use the canonical Lesson schema { lesson, context, evidence } — the
// shape the reflection-runner writes and context-assembler renders. Any other
// shape surfaces as "undefined: undefined" in soul_context's Active Lessons.
export const STARTER_LESSONS = [
  {
    id: "lesson-starter-01",
    lesson: "When the user asks a question and you're about to say 'typically' or 'usually', that's a signal to verify rather than guess. Read the actual file or docs.",
    context: "accuracy",
    source: "reflection",
    confidence: 0.85,
    evidence: [],
    createdAt: now - 10 * day,
    lastAppliedAt: now - 3 * day,
    applicationCount: 6,
  },
  {
    id: "lesson-starter-02",
    lesson: "Short user replies after long explanations ('ok', 'sure', 'thanks') often mean the explanation was longer than needed. Next time, lead with the answer.",
    context: "communication",
    source: "reflection",
    confidence: 0.79,
    evidence: [],
    createdAt: now - 8 * day,
    lastAppliedAt: now - 2 * day,
    applicationCount: 4,
  },
  {
    id: "lesson-starter-03",
    lesson: "When corrected, the real lesson is rarely 'get this specific fact right' — it's usually about a reasoning pattern that led to the wrong conclusion. Look one level up.",
    context: "learning",
    source: "reflection",
    confidence: 0.72,
    evidence: [],
    createdAt: now - 6 * day,
    lastAppliedAt: now - 4 * day,
    applicationCount: 3,
  },
  {
    id: "lesson-starter-04",
    lesson: "Testing code you wrote before reporting it done catches ~40% of issues that would otherwise require a correction cycle. The cost of running the test is always less than the cost of the back-and-forth.",
    context: "development",
    source: "reflection",
    confidence: 0.88,
    evidence: [],
    createdAt: now - 5 * day,
    lastAppliedAt: now - 1 * day,
    applicationCount: 8,
  },
  {
    id: "lesson-starter-05",
    lesson: "When multiple approaches exist, state the tradeoff in one sentence rather than listing all options. The user can redirect if your default doesn't match their constraints.",
    context: "communication",
    source: "reflection",
    confidence: 0.68,
    evidence: [],
    createdAt: now - 4 * day,
    lastAppliedAt: now - 2 * day,
    applicationCount: 3,
  },
];

export const STARTER_META = {
  phase: "apprentice",
  reflectionCount: 8,
  frameworkSurvivalRate: 0.83,
  lastPhaseTransition: now - 14 * day,
  signalVelocity: 3.2,
  avgReflectionQuality: 0.7,
};

export const STARTER_TENSIONS = {
  tensions: [
    {
      id: "tension-starter-01",
      frameworkA: "fw-starter-03",
      frameworkB: "fw-starter-05",
      description: "Minimal Viable Change says 'make the smallest fix' but Fail Fast Fail Loud says 'add explicit error handling'. Sometimes proper error handling IS the minimal change, but sometimes it's scope creep. Resolution: error handling at system boundaries is minimal; error handling for internal invariants is optional.",
      preferredInContext: {},
      status: "holding" as const,
      detectedAt: now - 7 * day,
    },
  ],
};
